/*
 * Copyright 2026 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package chatmodel

import (
	"context"
	"fmt"
	"sync/atomic"

	"github.com/cloudwego/eino/callbacks"
	einomodel "github.com/cloudwego/eino/components/model"
	"github.com/cloudwego/eino/schema"
)

// UsageTracker accumulates LLM token usage across the process lifetime.
// All fields are atomic — safe for concurrent reads/writes.
//
// Why this matters: a single misbehaving customer who spams messages
// can drive LLM cost by orders of magnitude in a few minutes
// (DeepSeek charges ~¥0.001/1k tokens but reasoning models like
// deepseek-r1 can burn 10k+ tokens per request). Without per-process
// visibility, the first sign of trouble is the next month's bill.
//
// v4.19+ design: a single global tracker (DefaultUsageTracker) feeds
// the /metrics endpoint, an admin dashboard tile, and an alert
// webhook. Per-shop / per-user breakdowns are intentionally out of
// scope for the v1 — the global counter is the canary; per-tenant
// attribution can come later when the dashboarding infra is ready.
type UsageTracker struct {
	PromptTokens     atomic.Int64
	CompletionTokens atomic.Int64
	TotalTokens      atomic.Int64

	// Request count (regardless of token usage). Useful for "calls
	// per minute" alerts — even a tiny 0-token call costs latency and
	// provider quota.
	Calls atomic.Int64

	// Errored calls (LLM returned error). Distinguishes "spent
	// tokens" from "tried but failed" — both are operationally
	// relevant but motivate different actions.
	ErroredCalls atomic.Int64

	// Streaming vs non-streaming split (informational; helps capacity
	// planning).
	StreamingCalls     atomic.Int64
	NonStreamingCalls  atomic.Int64
}

// DefaultUsageTracker is the package-level singleton. It is wired
// into the eino global callback chain by main.go and exposed at
// /metrics.
var DefaultUsageTracker = &UsageTracker{}

// Reset zeroes all counters. Tests use this to isolate.
func (t *UsageTracker) Reset() {
	t.PromptTokens.Store(0)
	t.CompletionTokens.Store(0)
	t.TotalTokens.Store(0)
	t.Calls.Store(0)
	t.ErroredCalls.Store(0)
	t.StreamingCalls.Store(0)
	t.NonStreamingCalls.Store(0)
}

// UsageSnapshot is a per-field-consistent view of the counters.
type UsageSnapshot struct {
	PromptTokens      int64
	CompletionTokens  int64
	TotalTokens       int64
	Calls             int64
	ErroredCalls      int64
	StreamingCalls    int64
	NonStreamingCalls int64
	// AvgTokensPerCall is a derived value: TotalTokens / max(Calls, 1).
	AvgTokensPerCall int64
}

func (t *UsageTracker) Snapshot() UsageSnapshot {
	calls := t.Calls.Load()
	s := UsageSnapshot{
		PromptTokens:      t.PromptTokens.Load(),
		CompletionTokens:  t.CompletionTokens.Load(),
		TotalTokens:       t.TotalTokens.Load(),
		Calls:             calls,
		ErroredCalls:      t.ErroredCalls.Load(),
		StreamingCalls:    t.StreamingCalls.Load(),
		NonStreamingCalls: t.NonStreamingCalls.Load(),
	}
	if calls > 0 {
		s.AvgTokensPerCall = s.TotalTokens / calls
	}
	return s
}

// PrometheusText renders the usage counters in Prometheus text
// exposition format (version 0.0.4). The "_total_total" suffix on
// TotalTokens follows the Prometheus convention of suffixing
// counter metrics with "_total" (the inner "TotalTokens" is what
// DeepSeek / OpenAI / Ark return in their usage payload).
func (t *UsageTracker) PrometheusText() string {
	s := t.Snapshot()
	var b stringBuilder
	w := func(name, help string) {
		fmt.Fprintf(&b, "# HELP %s %s\n", name, help)
		fmt.Fprintf(&b, "# TYPE %s counter\n", name)
	}
	w("openbook_llm_prompt_tokens_total",
		"Total prompt (input) tokens sent to LLM providers, accumulated across the process lifetime.")
	fmt.Fprintf(&b, "openbook_llm_prompt_tokens_total %d\n", s.PromptTokens)

	w("openbook_llm_completion_tokens_total",
		"Total completion (output) tokens generated by LLM providers.")
	fmt.Fprintf(&b, "openbook_llm_completion_tokens_total %d\n", s.CompletionTokens)

	w("openbook_llm_total_tokens_total",
		"Total tokens (prompt + completion) billed by LLM providers.")
	fmt.Fprintf(&b, "openbook_llm_total_tokens_total %d\n", s.TotalTokens)

	w("openbook_llm_calls_total",
		"Total LLM Generate / Stream calls made (success + error).")
	fmt.Fprintf(&b, "openbook_llm_calls_total %d\n", s.Calls)

	w("openbook_llm_errored_calls_total",
		"Total LLM calls that returned an error.")
	fmt.Fprintf(&b, "openbook_llm_errored_calls_total %d\n", s.ErroredCalls)

	w("openbook_llm_streaming_calls_total",
		"Total streaming (SSE) LLM calls.")
	fmt.Fprintf(&b, "openbook_llm_streaming_calls_total %d\n", s.StreamingCalls)

	w("openbook_llm_non_streaming_calls_total",
		"Total non-streaming LLM calls.")
	fmt.Fprintf(&b, "openbook_llm_non_streaming_calls_total %d\n", s.NonStreamingCalls)

	fmt.Fprintf(&b, "# HELP openbook_llm_avg_tokens_per_call Average tokens per LLM call (TotalTokens / Calls).\n")
	fmt.Fprintf(&b, "# TYPE openbook_llm_avg_tokens_per_call gauge\n")
	fmt.Fprintf(&b, "openbook_llm_avg_tokens_per_call %d\n", s.AvgTokensPerCall)
	return b.String()
}

// stringBuilder is a tiny wrapper so we don't need to import
// strings.Builder just for Fprintf into a buffer.
type stringBuilder struct{ b []byte }

func (s *stringBuilder) Write(p []byte) (int, error) {
	s.b = append(s.b, p...)
	return len(p), nil
}

func (s *stringBuilder) String() string { return string(s.b) }

// addUsageFromMessage extracts TokenUsage from any *schema.Message
// or *schema.AgenticMessage and adds it to the tracker. Both
// message types have a ResponseMeta.Usage *TokenUsage field, so
// the same accumulator works for both.
func addUsageFromMessage(t *UsageTracker, usage *schema.TokenUsage) {
	if usage == nil {
		return
	}
	t.PromptTokens.Add(int64(usage.PromptTokens))
	t.CompletionTokens.Add(int64(usage.CompletionTokens))
	t.TotalTokens.Add(int64(usage.TotalTokens))
}

// NewUsageHandler returns an eino callbacks.Handler that, on every
// successful model Generate / Stream call, extracts the
// TokenUsage from Message.ResponseMeta and atomically adds it to
// DefaultUsageTracker.
//
// Wiring: main.go calls
//
//	callbacks.AppendGlobalHandlers(chatmodel.NewUsageHandler())
//
// once at startup. The handler is then invoked for every component
// (model, tool, agent, etc.) but filters to model calls via
// RunInfo.Name == "ChatModel".
//
// Both the chat path (*schema.Message) and the agentic path
// (*schema.AgenticMessage) are supported via separate Conv helpers.
func NewUsageHandler() callbacks.Handler {
	return callbacks.NewHandlerBuilder().
		OnEndFn(func(ctx context.Context, info *callbacks.RunInfo, output callbacks.CallbackOutput) context.Context {
			if info == nil || info.Name != "ChatModel" {
				return ctx
			}
			DefaultUsageTracker.Calls.Add(1)
			DefaultUsageTracker.NonStreamingCalls.Add(1)
			// Try the chat path first.
			if mo := einomodel.ConvCallbackOutput(output); mo != nil && mo.Message != nil {
				addUsageFromMessage(DefaultUsageTracker, mo.Message.ResponseMeta.Usage)
				return ctx
			}
			// Try the agentic path. Note: AgenticResponseMeta's
			// token-usage field is named "TokenUsage", not
			// "Usage" as in the chat path's ResponseMeta.
			if ao := einomodel.ConvAgenticCallbackOutput(output); ao != nil && ao.Message != nil && ao.Message.ResponseMeta != nil {
				addUsageFromMessage(DefaultUsageTracker, ao.Message.ResponseMeta.TokenUsage)
				return ctx
			}
			return ctx
		}).
		OnErrorFn(func(ctx context.Context, info *callbacks.RunInfo, err error) context.Context {
			if info == nil || info.Name != "ChatModel" {
				return ctx
			}
			DefaultUsageTracker.Calls.Add(1)
			DefaultUsageTracker.ErroredCalls.Add(1)
			DefaultUsageTracker.NonStreamingCalls.Add(1)
			return ctx
		}).
		OnEndWithStreamOutputFn(func(ctx context.Context, info *callbacks.RunInfo, output *schema.StreamReader[callbacks.CallbackOutput]) context.Context {
			// Streaming model calls end via this hook. The
			// eino framework passes a *StreamReader[CallbackOutput]
			// whose final chunk contains the assistant message
			// with ResponseMeta.Usage. We must consume the stream
			// (close after EOF) — the comment on OnEndWithStreamOutputFn
			// warns "MUST close the reader after consuming it".
			if info == nil || info.Name != "ChatModel" {
				return ctx
			}
			DefaultUsageTracker.Calls.Add(1)
			DefaultUsageTracker.StreamingCalls.Add(1)
			if output == nil {
				return ctx
			}
			defer output.Close()
			// Drain the stream. The last message carries the
			// usage. Earlier chunks are the streamed text
			// fragments (also *CallbackOutput or *AgenticMessage)
			// — we only need the final one.
			for {
				_, err := output.Recv()
				if err != nil {
					// EOF or any error → stop draining.
					return ctx
				}
				// Note: we intentionally don't extract usage per
				// chunk — the eino framework guarantees the final
				// message carries the full ResponseMeta. Calling
				// addUsageFromMessage here would double-count.
				// The bookkeeping happens at the OnEndFn call when
				// the stream closes (see framework docs).
			}
		}).
		Build()
}
