/*
 * Copyright 2026 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package sensitive

import (
	"os"
	"path/filepath"
	"testing"
)

func TestLoadProductionWords_RealFile(t *testing.T) {
	// Verify the bundled words_zh.json loads without error and registers
	// its words. The file is regenerated by `go run ./cmd/sensitive-gen`
	// from the Sensitive-lexicon project.
	Reset()
	defer Reset()

	if err := LoadProductionWords(); err != nil {
		t.Fatalf("LoadProductionWords: %v", err)
	}

	// The bundled file should have the "general" category populated with
	// at least a few hundred words.
	cats := Categories()
	if len(cats) == 0 {
		t.Error("expected at least one category after loading, got 0")
	}
	// Confirm the general bucket has plenty of words (the file has ~1900).
	found := false
	for _, c := range cats {
		if c == "general" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected 'general' category, got: %v", cats)
	}
}

func TestLoadProductionWords_MissingFile(t *testing.T) {
	// Point the env var at a path that doesn't exist; should be a no-op,
	// not an error.
	t.Setenv("OPENBOOK_SENSITIVE_WORDS", filepath.Join(os.TempDir(), "nope-does-not-exist.json"))
	if err := LoadProductionWords(); err != nil {
		t.Errorf("missing file should be a no-op, got: %v", err)
	}
}

func TestLoadProductionWords_EnvOverridePath(t *testing.T) {
	// Write a tiny custom JSON to a temp file, point env at it, verify
	// the words land in the checker.
	dir := t.TempDir()
	path := filepath.Join(dir, "custom.json")
	custom := `{"version":"vTest","categories":{"politics":["testword_unique_xyz"]}}`
	if err := os.WriteFile(path, []byte(custom), 0644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("OPENBOOK_SENSITIVE_WORDS", path)
	Reset()
	defer Reset()

	if err := LoadProductionWords(); err != nil {
		t.Fatalf("LoadProductionWords: %v", err)
	}
	if r := Check("contains testword_unique_xyz"); !r.Blocked {
		t.Errorf("custom word should be blocked, got %+v", r)
	}
}
